export const GEOGRAPHIC_ACTIVITY = [
  { label: 'Auvergne Rhône-Alpes', value: 'Auvergne-Rhône-Alpes' },
  { label: 'Ain', value: 'Ain' },
  { label: 'Allier', value: 'Allier' },
  { label: 'Ardèche', value: 'Ardèche' },
  { label: 'Cantal', value: 'Cantal' },
  { label: 'Drôme', value: 'Drôme' },
  { label: 'Haute-Savoie', value: 'Haute-Savoie' },
  { label: 'Haute Loire', value: 'Haute-Loire' },
  { label: 'Isère', value: 'Isère' },
  { label: 'Loire', value: 'Loire' },
  { label: 'Puy De Dôme', value: 'Puy-de-Dôme' },
  { label: 'Rhône', value: 'Rhône' },
  { label: 'Savoie', value: 'Savoie' },
];
