import type { ThemeTypes } from '@/types/themeTypes/ThemeType';

const BLUE_THEME: ThemeTypes = {
  name: 'BLUE_THEME',
  dark: false,
  variables: {
    'border-color': '#e5eaef',
    'border-opacity': 1,
  },
  colors: {
    primary: '#0085db',
    secondary: '#707a82',
    thirdy: '#5d79a4',
    info: '#46caeb',
    success: '#4bd08b',
    warning: '#f8c076',
    mimosa: '#fabe4a',
    error: '#fb977d',
    indigo: '#8763da',
    lightprimary: '#f39454',
    lightinfo: '#e1f5fa',
    lightsecondary: '#e7ecf0',
    lightsuccess: '#6a994e',
    lighterror: '#e34632',
    lightwarning: '#fff6ea',
    lightindigo: '#f1ebff',
    textPrimary: '#2A3547',
    textSecondary: '#2A3547',
    borderColor: '#e5eaef',
    inputBorder: '#DFE5EF',
    containerBg: '#ffffff',
    background: '#fff5eb',
    hoverColor: '#f6f9fc',
    surface: '#fff',
    grey100: '#707a82',
    grey200: '#111c2d',
    darkbg: '#2a3447',
    bglight: '#f5f8fb',
    bgdark: '#111c2d',
  },
};

const AQUA_THEME: ThemeTypes = {
  name: 'AQUA_THEME',
  dark: false,
  variables: {
    'border-color': '#e5eaef',
    'border-opacity': 1,
  },
  colors: {
    primary: '#5d79a4',
    secondary: '#47D7BC',
    thirdy: '#f39454',
    info: '#46caeb',
    success: '#4bd08b',
    warning: '#f8c076',
    error: '#fb977d',
    indigo: '#8763da',
    lightprimary: '#f39454',
    lightinfo: '#e1f5fa',
    lightsecondary: '#e7ecf0',
    lightsuccess: '#dffff3',
    lighterror: '#ffede9',
    lightwarning: '#fff6ea',
    lightindigo: '#f1ebff',
    textPrimary: '#2A3547',
    textSecondary: '#5d79a4',
    borderColor: '#e5eaef',
    inputBorder: '#DFE5EF',
    containerBg: '#ffffff',
    mimosa: '#fabe4a',
    background: '#f0f5f9',
    hoverColor: '#f6f9fc',
    surface: '#fff',
    grey100: '#707a82',
    grey200: '#111c2d',
    darkbg: '#2a3447',
    bglight: '#f5f8fb',
    bgdark: '#293b57',
  },
};

const PURPLE_THEME: ThemeTypes = {
  name: 'PURPLE_THEME',
  dark: false,
  variables: {
    'border-color': '#e5eaef',
    'border-opacity': 1,
  },
  colors: {
    primary: '#763EBD',
    secondary: '#95CFD5',
    info: '#46caeb',
    success: '#4bd08b',
    mimosa: '#fabe4a',

    warning: '#f8c076',
    error: '#fb977d',
    indigo: '#8763da',
    lightprimary: '#f39454',
    lightinfo: '#e1f5fa',
    lightsecondary: '#e7ecf0',
    lightsuccess: '#dffff3',
    lighterror: '#ffede9',
    lightwarning: '#fff6ea',
    lightindigo: '#f1ebff',
    textPrimary: '#2A3547',
    textSecondary: '#2A3547',
    borderColor: '#e5eaef',
    inputBorder: '#DFE5EF',
    containerBg: '#ffffff',
    background: '#f0f5f9',
    hoverColor: '#f6f9fc',
    surface: '#fff',
    grey100: '#707a82',
    grey200: '#111c2d',
    darkbg: '#2a3447',
    bglight: '#f5f8fb',
    bgdark: '#111c2d',
  },
};

const GREEN_THEME: ThemeTypes = {
  name: 'GREEN_THEME',
  dark: false,
  variables: {
    'border-color': '#e5eaef',
    'border-opacity': 1,
  },
  colors: {
    primary: '#0A7EA4',
    secondary: '#CCDA4E',
    info: '#46caeb',
    success: '#4bd08b',
    warning: '#f8c076',
    mimosa: '#fabe4a',

    error: '#fb977d',
    indigo: '#8763da',
    lightprimary: '#e5f3fb',
    lightinfo: '#e1f5fa',
    lightsecondary: '#e7ecf0',
    lightsuccess: '#dffff3',
    lighterror: '#ffede9',
    lightwarning: '#fff6ea',
    lightindigo: '#f1ebff',
    textPrimary: '#2A3547',
    textSecondary: '#2A3547',
    borderColor: '#e5eaef',
    inputBorder: '#DFE5EF',
    containerBg: '#ffffff',
    background: '#f0f5f9',
    hoverColor: '#f6f9fc',
    surface: '#fff',
    grey100: '#707a82',
    grey200: '#111c2d',
    darkbg: '#2a3447',
    bglight: '#f5f8fb',
    bgdark: '#111c2d',
  },
};

const CYAN_THEME: ThemeTypes = {
  name: 'CYAN_THEME',
  dark: false,
  variables: {
    'border-color': '#e5eaef',
    'border-opacity': 1,
  },
  colors: {
    primary: '#01C0C8',
    secondary: '#FB9678',
    info: '#46caeb',
    success: '#4bd08b',
    warning: '#f8c076',
    mimosa: '#fabe4a',

    error: '#fb977d',
    indigo: '#8763da',
    lightprimary: '#e5f3fb',
    lightinfo: '#e1f5fa',
    lightsecondary: '#e7ecf0',
    lightsuccess: '#dffff3',
    lighterror: '#ffede9',
    lightwarning: '#fff6ea',
    lightindigo: '#f1ebff',
    textPrimary: '#2A3547',
    textSecondary: '#2A3547',
    borderColor: '#e5eaef',
    inputBorder: '#DFE5EF',
    containerBg: '#ffffff',
    background: '#f0f5f9',
    hoverColor: '#f6f9fc',
    surface: '#fff',
    grey100: '#707a82',
    grey200: '#111c2d',
    darkbg: '#2a3447',
    bglight: '#f5f8fb',
    bgdark: '#111c2d',
  },
};

const ORANGE_THEME: ThemeTypes = {
  name: 'ORANGE_THEME',
  dark: false,
  variables: {
    'border-color': '#e5eaef',
    'border-opacity': 1,
  },
  colors: {
    primary: '#FA896B',
    secondary: '#0074BA',
    mimosa: '#fabe4a',

    info: '#46caeb',
    success: '#4bd08b',
    warning: '#f8c076',
    error: '#fb977d',
    indigo: '#8763da',
    lightprimary: '#e5f3fb',
    lightinfo: '#e1f5fa',
    lightsecondary: '#e7ecf0',
    lightsuccess: '#dffff3',
    lighterror: '#ffede9',
    lightwarning: '#fff6ea',
    lightindigo: '#f1ebff',
    textPrimary: '#2A3547',
    textSecondary: '#2A3547',
    borderColor: '#e5eaef',
    inputBorder: '#DFE5EF',
    containerBg: '#ffffff',
    background: '#f0f5f9',
    hoverColor: '#f6f9fc',
    surface: '#fff',
    grey100: '#707a82',
    grey200: '#111c2d',
    darkbg: '#2a3447',
    bglight: '#f5f8fb',
    bgdark: '#111c2d',
  },
};

export { AQUA_THEME, BLUE_THEME, CYAN_THEME, GREEN_THEME, ORANGE_THEME, PURPLE_THEME };
