import type { Attendance } from '@/types/components/school-pages/attendance';
import { CheckIcon, MinusIcon, XIcon } from 'vue-tabler-icons';
import img1 from '/images/profile/1.jpg';
import img2 from '/images/profile/2.jpg';
import img3 from '/images/profile/3.jpg';
import img4 from '/images/profile/4.jpg';
import img5 from '/images/profile/5.jpg';
import img6 from '/images/profile/6.jpg';

const AttendanceData: Attendance[] = [
  {
    avatar: img4,
    name: 'Garima Singh',
    class: '10',
    day1: CheckIcon,
    day2: CheckIcon,
    day3: CheckIcon,
    day4: XIcon,
    day5: CheckIcon,
    day6: CheckIcon,
    day7: MinusIcon,
    day8: XIcon,
    day9: CheckIcon,
    day10: CheckIcon,
    day11: CheckIcon,
    day12: CheckIcon,
    day13: XIcon,
    day14: MinusIcon,
    day15: CheckIcon,
    day16: CheckIcon,
    day17: CheckIcon,
    day18: XIcon,
    day19: CheckIcon,
    day20: CheckIcon,
    day21: MinusIcon,
    day22: CheckIcon,
    day23: CheckIcon,
    day24: XIcon,
    day25: CheckIcon,
    day26: CheckIcon,
    day27: CheckIcon,
    day28: MinusIcon,
    day29: CheckIcon,
    day30: CheckIcon,
  },
  {
    avatar: img5,
    name: 'John Deo',
    class: '12',
    day1: CheckIcon,
    day2: CheckIcon,
    day3: CheckIcon,
    day4: XIcon,
    day5: CheckIcon,
    day6: CheckIcon,
    day7: MinusIcon,
    day8: XIcon,
    day9: CheckIcon,
    day10: CheckIcon,
    day11: CheckIcon,
    day12: CheckIcon,
    day13: XIcon,
    day14: MinusIcon,
    day15: CheckIcon,
    day16: CheckIcon,
    day17: CheckIcon,
    day18: XIcon,
    day19: CheckIcon,
    day20: CheckIcon,
    day21: MinusIcon,
    day22: CheckIcon,
    day23: CheckIcon,
    day24: XIcon,
    day25: CheckIcon,
    day26: CheckIcon,
    day27: CheckIcon,
    day28: MinusIcon,
    day29: CheckIcon,
    day30: CheckIcon,
  },
  {
    avatar: img3,
    name: 'Mark J. Freeman',
    class: '2',
    day1: CheckIcon,
    day2: CheckIcon,
    day3: CheckIcon,
    day4: XIcon,
    day5: CheckIcon,
    day6: CheckIcon,
    day7: MinusIcon,
    day8: XIcon,
    day9: CheckIcon,
    day10: CheckIcon,
    day11: CheckIcon,
    day12: CheckIcon,
    day13: XIcon,
    day14: MinusIcon,
    day15: CheckIcon,
    day16: CheckIcon,
    day17: CheckIcon,
    day18: XIcon,
    day19: CheckIcon,
    day20: CheckIcon,
    day21: MinusIcon,
    day22: CheckIcon,
    day23: CheckIcon,
    day24: XIcon,
    day25: CheckIcon,
    day26: CheckIcon,
    day27: CheckIcon,
    day28: MinusIcon,
    day29: CheckIcon,
    day30: CheckIcon,
  },
  {
    avatar: img2,
    name: 'Mark Maria',
    class: '2',
    day1: CheckIcon,
    day2: CheckIcon,
    day3: CheckIcon,
    day4: XIcon,
    day5: CheckIcon,
    day6: CheckIcon,
    day7: MinusIcon,
    day8: XIcon,
    day9: CheckIcon,
    day10: CheckIcon,
    day11: CheckIcon,
    day12: CheckIcon,
    day13: XIcon,
    day14: MinusIcon,
    day15: CheckIcon,
    day16: CheckIcon,
    day17: CheckIcon,
    day18: XIcon,
    day19: CheckIcon,
    day20: CheckIcon,
    day21: MinusIcon,
    day22: CheckIcon,
    day23: CheckIcon,
    day24: XIcon,
    day25: CheckIcon,
    day26: CheckIcon,
    day27: CheckIcon,
    day28: MinusIcon,
    day29: CheckIcon,
    day30: CheckIcon,
  },
  {
    avatar: img1,
    name: 'Mark Willy',
    class: '8',
    day1: CheckIcon,
    day2: CheckIcon,
    day3: CheckIcon,
    day4: XIcon,
    day5: CheckIcon,
    day6: CheckIcon,
    day7: MinusIcon,
    day8: XIcon,
    day9: CheckIcon,
    day10: CheckIcon,
    day11: CheckIcon,
    day12: CheckIcon,
    day13: XIcon,
    day14: MinusIcon,
    day15: CheckIcon,
    day16: CheckIcon,
    day17: CheckIcon,
    day18: XIcon,
    day19: CheckIcon,
    day20: CheckIcon,
    day21: MinusIcon,
    day22: CheckIcon,
    day23: CheckIcon,
    day24: XIcon,
    day25: CheckIcon,
    day26: CheckIcon,
    day27: CheckIcon,
    day28: MinusIcon,
    day29: CheckIcon,
    day30: CheckIcon,
  },
  {
    avatar: img3,
    name: 'Nirav Joshi',
    class: '12',
    day1: CheckIcon,
    day2: CheckIcon,
    day3: CheckIcon,
    day4: XIcon,
    day5: CheckIcon,
    day6: CheckIcon,
    day7: MinusIcon,
    day8: XIcon,
    day9: CheckIcon,
    day10: CheckIcon,
    day11: CheckIcon,
    day12: CheckIcon,
    day13: XIcon,
    day14: MinusIcon,
    day15: CheckIcon,
    day16: CheckIcon,
    day17: CheckIcon,
    day18: XIcon,
    day19: CheckIcon,
    day20: CheckIcon,
    day21: MinusIcon,
    day22: CheckIcon,
    day23: CheckIcon,
    day24: XIcon,
    day25: CheckIcon,
    day26: CheckIcon,
    day27: CheckIcon,
    day28: MinusIcon,
    day29: CheckIcon,
    day30: CheckIcon,
  },
  {
    avatar: img4,
    name: 'Spark Doe',
    class: '6',
    day1: CheckIcon,
    day2: CheckIcon,
    day3: CheckIcon,
    day4: XIcon,
    day5: CheckIcon,
    day6: CheckIcon,
    day7: MinusIcon,
    day8: XIcon,
    day9: CheckIcon,
    day10: CheckIcon,
    day11: CheckIcon,
    day12: CheckIcon,
    day13: XIcon,
    day14: MinusIcon,
    day15: CheckIcon,
    day16: CheckIcon,
    day17: CheckIcon,
    day18: XIcon,
    day19: CheckIcon,
    day20: CheckIcon,
    day21: MinusIcon,
    day22: CheckIcon,
    day23: CheckIcon,
    day24: XIcon,
    day25: CheckIcon,
    day26: CheckIcon,
    day27: CheckIcon,
    day28: MinusIcon,
    day29: CheckIcon,
    day30: CheckIcon,
  },
  {
    avatar: img6,
    name: 'Violet Mendoza',
    class: '7',
    day1: CheckIcon,
    day2: CheckIcon,
    day3: CheckIcon,
    day4: XIcon,
    day5: CheckIcon,
    day6: CheckIcon,
    day7: MinusIcon,
    day8: XIcon,
    day9: CheckIcon,
    day10: CheckIcon,
    day11: CheckIcon,
    day12: CheckIcon,
    day13: XIcon,
    day14: MinusIcon,
    day15: CheckIcon,
    day16: CheckIcon,
    day17: CheckIcon,
    day18: XIcon,
    day19: CheckIcon,
    day20: CheckIcon,
    day21: MinusIcon,
    day22: CheckIcon,
    day23: CheckIcon,
    day24: XIcon,
    day25: CheckIcon,
    day26: CheckIcon,
    day27: CheckIcon,
    day28: MinusIcon,
    day29: CheckIcon,
    day30: CheckIcon,
  },
];

export { AttendanceData };
